### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by richross** [mikiest/sptools#1]
Are you planning to place the source code here as well?  Currently, there are only a couple of images and the documentation.  This is the only SharePoint extension for Code and would love to see this succeed.  

Thanks!

**Comment by smannina** [comment]
Thanks for creating this extension. I'm mainly concerned with creating on-premises SharePoint add-ins using Visual Studio Code. Will SPTools authenticate to an on-premises SharePoint 2013 farm which uses Kerberos?

**Comment by DevImpostor** [comment]
To piggy back off richross's comment, I'm very interested in this tool and really hope you publish the source. I've even created a console app that has similar syncing capabilities using the Client Object Model (C#) and have been waiting for VS Code to support plug-ins. I would gladly contribute to this project as I have a lot of ideas on this can be extended. Otherwise, I will have to consider writing and publishing my own. Hope to hear from you soon!

**Comment by SmoothKeys** [comment]
To piggy back off richross's comment, I'm very interested in this tool and really hope you publish the source. I've even created a console app that has similar syncing capabilities using the Client Object Model (C#) and have been waiting for VS Code to support a plug-ins. I would gladly contribute to this project as I have a lot of ideas on this can be extended. Otherwise, I will have to consider writing and publishing my own. Hope to hear from you soon!

**Comment by SmoothKeys** [comment]
To piggy back off richross's comment, I'm very interested in this tool and really hope you publish the source. I've even created a console app that has similar syncing capabilities using the Client Object Model (C#) and have been waiting for VS Code to support a plug-ins. I would gladly contribute to this project as I have a lot of ideas on this can be extended. Otherwise, I will have to consider writing and publishing my own. Hope to hear from you soon!

**Comment by richross** [comment]
I'm with SmoothKeys. Would be interested in contributing to this effort instead of going and starting a separate one.

**Comment by mikiest** [comment]
I'm on it guys, just need to tidy up a couple of things and it will be with you soon.

Thank you for your support :)

**Comment by mikiest** [comment]
@smannina I didn't have the opportunity to try it on a Kerberos authentication. Best thing to do now is to try it yourself and come back here with your feedback (possibly opening a new issue).

**Comment by DevImpostor** [comment]
@mikiest Great to hear, look forward to contributing...

**Comment by mikiest** [comment]
@SmoothKeys @richross Here we are.
Feel free to open other issues for any request/feedback/discussion.
